const ShopActionTypes = {
  REQUEST_CATEGORIES_PENDING: "REQUEST_CATEGORIES_PENDING",
  REQUEST_CATEGORIES_SUCCESS: "REQUEST_CATEGORIES_SUCCESS",
  REQUEST_CATEGORIES_FAILED: "REQUEST_CATEGORIES_FAILED",
  SET_CATEGORY_FACETS: "SET_CATEGORY_FACETS",
};

export default ShopActionTypes;
